version: '3'

services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - ch_ntw

  deephaven:
    container_name: deephaven
    build:
      context: .
      dockerfile: build/Dockerfile.deephaven
    environment:
      JAVA_OPTS: -Xmx24g -Dio.deephaven.app.GcApplication.enabled=true -Ddeephaven.application.dir=/data/storage/app.d
      START_OPS: -Ddeephaven.console.type=python
    ports:
      - "10000:10000"
    volumes:
      - ./data/deephaven:/data/storage
      - ./data/parquet:/data/parquet
    networks:
      - ch_ntw

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./build/init_trades.sql:/docker-entrypoint-initdb.d/init_trades.sql:ro
      - ./build/init_orderbooks.sql:/docker-entrypoint-initdb.d/init_orderbook.sql:ro
    networks:
        - ch_ntw

  cryptofeed:
    container_name: cryptofeed
    build:
      context: .
      dockerfile: build/Dockerfile.cryptofeed
    depends_on:
      - redpanda
    networks:
      - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24